services:
  # Our simple python service to test the environment
  logger:
    build:
      context: ./src/services/logger
    volumes:
      - ./src/services/logger:/app
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO